title: "GSEL — Geospatial Science and Engineering Lab"
author: Hunsoo Song
email: hunsoo.song@cbnu.ac.kr
description: "The official website of the Geospatial Science and Engineering Lab (GSEL)."

baseurl: "" # 도메인을 루트로 연결했으므로 빈 값
url: "https://gsel.xyz"

theme: minima

header_pages:
  - index.md
  - people.md
  - research.md
  - publications.md
  - openings.md
  - kr/index.md

plugins:
  - jekyll-feed

